[project]
name = "mspm"
version = "2.1.0"
description = "A command-line package manager for Minecraft server plugins."
authors = [
    { name = "Nikita Denissov", email = "n.denissov@proton.me" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities"
]
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "tomli (>=2.3.0,<3.0.0)",
    "tomli-w (>=1.2.0,<2.0.0)",
    "packaging (>=25.0,<26.0)",
    "rich (>=14.2.0,<15.0.0)",
    "cloudscraper (>=1.2.71,<2.0.0)",
    "ujson (>=5.11.0,<6.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "selenium (>=4.39.0,<5.0.0)",
    "webdriver-manager (>=4.0.2,<5.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/ndenissov/mspm"

[project.scripts]
mspm = "mspm.cli:main"